### ISSUE TITLE
Hamburger menu is hard to click

### ISSUE THREAD

**Issue by jcubic** [illustrated-machine-learning/illustrated-machine-learning.github.io#12]
It looks like you need to click on the black color to open the menu, the white part is not clickable so you need to move the mouse and click when the cursor changes. Which is pretty annoying.

I was investigating and it seems that the clickable label doesn't contain the first top bar of the icon so the space between the top and middle bar is not clickable.

To fix this all you have to do is to add:

```css
top: 8px;
```

to the span which creates the horizontal bar.

**Comment by francescodisalvo05** [comment]
Hey @jcubic, you're totally right, it was easier than I thought, thank you! 
I fixed it through the last commit, therefore I am closing this issue 🚀
